WANdisco/wandisco-documentation

- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
These changes are from the recent peer review.
> Sandbox review

- docs/quickstarts/preparation/azure_vm_creation.md
I've tested this and it appears to work as expected.
> Azure VM creation - location flag added

- docs/quickstarts/operation/consistency-check.md
- docs/quickstarts/operation/create-rule.md
- website/sidebars.json
> Consistency Check section

- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
Live Hive rule creation via OneUI.
> HDP Sandbox to Databricks - LHV rule changes

- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
- docs/quickstarts/operation/hdp_sandbox_fusion_stop_start.md
- docs/quickstarts/troubleshooting/hdp_sandbox_lan_troubleshooting.md
- docs/quickstarts/troubleshooting/useful_info.md
Touched on a few documents based on feedback.
> Refinement of HDP Sandbox to Databricks QS and linked documents

- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
- docs/quickstarts/operation/consistency-check.md
- docs/quickstarts/operation/create-rule.md
- docs/quickstarts/troubleshooting/hdp_sandbox_lan_troubleshooting.md
- docs/quickstarts/troubleshooting/useful_info.md
Tested the links within Github on this branch and they work correctly now.
> Internal link fixes for HDP Sandbox to Databricks and related docs

- docs/quickstarts/troubleshooting/useful_info.md
Some changes to the original commands used.
> Updates to Useful Information page

- docs/quickstarts/troubleshooting/hdp_sandbox_lan_troubleshooting.md
Addition to the HDP Sandbox to Databricks Troubleshooting guide.
> No Route to Host - Troubleshooting addition

- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
Minor change to HDP Sandbox to Databricks doc.
> Pre-req change for Databricks

- docs/docs/databricks_config.md
Given it a first go, happy for feedback.
> Databricks config page

- docs/quickstarts/troubleshooting/hdp_sandbox_lan_troubleshooting.md
Decided to remove the relative link as the steps change quite a bit from the generic rebuild steps.
> HDP Sandbox to Databricks Rebuild improvements

- docs/quickstarts/preparation/azure_vm_creation.md
@benofbrown This works for me now, but perhaps could do with a technical look over.
@catrionabarker Need to understand whether enough info is provided (or too much has been provided).
> Azure VM Creation - script replacement

- docs/quickstarts/installation/cdh-adls2.md
- docs/quickstarts/installation/hdp-adlsg2.md
- docs/quickstarts/installation/hdp_sandbox-adlsg2_lm.md
- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
Also included changes from 'demo' to 'install' in various docs.
> CDH to ADLS Gen2 refresh

- docs/quickstarts/preparation/azure_vm_creation.md
- website/package-lock.json
- website/package.json
> Downloadable cloud-init.txt

- docs/quickstarts/installation/hdp_sandbox-adlsg2_lm.md
> Link added to HDP Sandbox to ADLS Gen2 LM QS

- docs/quickstarts/installation/adlsg1-adlsg2.md
- docs/quickstarts/installation/cdh-adls2.md
- docs/quickstarts/installation/hdp-adlsg2.md
- docs/quickstarts/installation/hdp_sandbox-adlsg2_ld.md
- docs/quickstarts/installation/hdp_sandbox-adlsg2_lm.md
- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
Also included some numbered step adjustments to make it inline with Style Guide.
Will merge into master once this is approved.
> Update QSs for new setup prompt

- docs/assets/cloud-init-adlm.txt
Straight to master due to raw link to master branch (assets) in ADLM docs.
> cloud-init-adlm.txt added to assets

- docs/quickstarts/installation/adlsg1-adlsg2.md
- docs/quickstarts/installation/cdh-adls2.md
- docs/quickstarts/installation/hdp-adlsg2.md
- docs/quickstarts/installation/hdp_sandbox-adlsg2_ld.md
- docs/quickstarts/installation/hdp_sandbox-adlsg2_lm.md
- docs/quickstarts/installation/hdp_sandbox_lhv_client-adlsg2_lan.md
- docs/quickstarts/preparation/vm_prep.md
- website/sidebars.json
Adjusted the links in all the other QSs as well.
> Made Azure VM Prep not specific to Azure

- docs/style-guide.md
Let me know if this isn't clear enough.
> Downloadable files to style guide

- docs/quickstarts/installation/hdp_sandbox-s3_ld.md
- docs/quickstarts/installation/hdp_sandbox-s3_lm.md
- docs/quickstarts/installation/s3-adlsg2_bi_lm.md
- website/sidebars.json
Develop needs to be PRed to master afterwards (no recent changes so should be fine).
> AWS S3 guides

- docs/quickstarts/installation/sandboxes/cdh-sandbox/cdh_sandbox-adlsg2_ld.md
- docs/quickstarts/installation/sandboxes/cdh-sandbox/cdh_sandbox-adlsg2_lm.md
- docs/quickstarts/installation/sandboxes/cdh-sandbox/cdh_sandbox-s3_ld.md
- docs/quickstarts/installation/sandboxes/cdh-sandbox/cdh_sandbox-s3_lm.md
- docs/quickstarts/installation/sandboxes/cdh-sandbox/cdh_sandbox_lhv_client-adlsg2_lan.md
- docs/quickstarts/installation/sandboxes/hdp-sandbox/hdp_sandbox-adlsg2_ld.md
- docs/quickstarts/installation/sandboxes/hdp-sandbox/hdp_sandbox-adlsg2_lm.md
- docs/quickstarts/installation/sandboxes/hdp-sandbox/hdp_sandbox-s3_ld.md
- docs/quickstarts/installation/sandboxes/hdp-sandbox/hdp_sandbox-s3_lm.md
- docs/quickstarts/installation/sandboxes/hdp-sandbox/hdp_sandbox_lhv_client-adlsg2_lan.md
to current state of setup-env.sh
> DAP-312 updated documentation

- docs/quickstarts/operation/advanced-settings.md
- website/sidebars.js
* Advanced settings reference
* Update advanced-settings.md
> Advanced settings reference (#122)

- website/sidebars.js
> Sidebars change for LiveData Plane

- docs/quickstarts/installation/adlsg1-adlsg2.md
- docs/quickstarts/installation/s3-adlsg2_bi.md
As discussed. simple link fixes.
> DOCU-803, DOCU-789 updating hyphens to underscores to fix links
